Implement feedback on pull request

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -22,11 +22,11 @@ jobs:
       - name: Clean
         run: rm src/bindings.rs
       - name: Generate bindings
-        run: cd bindings_generator && cargo run
+        run: cargo r -p bindings_generator
       - name: Upload crate source
         uses: actions/upload-artifact@v4
         with:
           name: crate-source
           path: src/
       - name: Diff generated Rust code
-        run: test -z "$(git status --porcelain)" || (echo "::error::Generated files are different, please regenerate with cargo run -p generate_bindings!"; git status; false)
+        run: test -z "$(git status --porcelain)" || (echo "::error::Generated files are different, please regenerate with cargo run -p generate_bindings!"; git diff; false)
