⚙️ Major refactor to use automatically generated bindings (#11)
* Update headers to 1.0

* Add placeholder bindings for new function in metalirconverter 1.0

* Update to 1.1

* Add functions to IRObject and IRCompiler

* Remove inconsistent symbol IRCompilerSetIntRTMask

* Use &CStr instead of &str

* Remove dbg! spam

* Change entry_point &[u8] to &CStr in alloc_compile_and_link

* Use bindings instead of redefining enums

* Major refactor to use automatically generated bindings

* Remove more duplicate structs

* Fix headers

They had the wrong whitespaceing and wrong version number

* Implement feedback on pull request

* Un-hardcode include directory

* Remove unnecessary to_string() call

* Change anon fields prefix

* Remove unnecessary bingden parameter

* Temporarily move example back

This makes this PR a bit smaller

* Clean-up

* Postpone adding new functions

* rename _bindgen_ty to _u

* Add trailing newline

* Add categories and keywords to Cargo.toml

* Put bindgen generated types behind ::ffi

* Make doc comment struct references monospace

Co-authored-by: Marijn Suijten <marijn@traverseresearch.nl>

* Remove unnecessary saxaboom specification

Co-authored-by: Marijn Suijten <marijn@traverseresearch.nl>

* Add callback function to bindgen to clean up enum variant names

* Fix trailing whitespaces and use is_ascii_digit

* Fix trailing newlines

* Update keywords

* Allow clippy::missing_safety_doc for bindings.rs

* Make CI happy

---------

Co-authored-by: Marijn Suijten <marijn@traverseresearch.nl>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -14,3 +14,20 @@ jobs:
         run: cargo clippy --workspace --all-targets -- -D warnings
       - name: Cargo test
         run: cargo test --workspace
+
+  generate-rust:
+    name: Generate Rust crate
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - name: Clean
+        run: rm src/bindings.rs
+      - name: Generate bindings
+        run: cargo r -p bindings_generator
+      - name: Upload crate source
+        uses: actions/upload-artifact@v4
+        with:
+          name: crate-source
+          path: src/
+      - name: Diff generated Rust code
+        run: test -z "$(git status --porcelain)" || (echo "::error::Generated files are different, please regenerate with cargo run -p generate_bindings!"; git diff; false)
